services:
  chat-api:
    container_name: loading_chat_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:

      SPRING_DATASOURCE_URL: jdbc:postgresql://chat-db:5432/chatdb
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

      GOOGLE_API_KEY: ${GOOGLE_API_KEY}

      APP_JWTSECRET: ${JWT_SECRET}

    depends_on:
      chat-db:
        condition: service_healthy
    networks:
      - chat-network

  chat-db:
    container_name: loading_chat_db
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: chatdb
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chat-network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d chatdb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  chat-network:
    driver: bridge